2018-03-17 14:20:06.809755: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/home/ubuntu/.local/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Best: 0.978098 using {'optimizer': 'adam', 'batch_size': 15, 'second_layer': 8, 'first_layer': 8}
0.976701 (0.010139) with: {'optimizer': 'adam', 'batch_size': 15, 'second_layer': 0, 'first_layer': 8}
0.978098 (0.007737) with: {'optimizer': 'adam', 'batch_size': 15, 'second_layer': 8, 'first_layer': 8}
0.700860 (0.387729) with: {'optimizer': 'adam', 'batch_size': 15, 'second_layer': 12, 'first_layer': 8}
0.683875 (0.415999) with: {'optimizer': 'adam', 'batch_size': 15, 'second_layer': 0, 'first_layer': 12}
0.976534 (0.009061) with: {'optimizer': 'adam', 'batch_size': 15, 'second_layer': 8, 'first_layer': 12}
0.977707 (0.008635) with: {'optimizer': 'adam', 'batch_size': 15, 'second_layer': 12, 'first_layer': 12}
0.971058 (0.006795) with: {'optimizer': 'adam', 'batch_size': 15, 'second_layer': 0, 'first_layer': 16}
0.974746 (0.011170) with: {'optimizer': 'adam', 'batch_size': 15, 'second_layer': 8, 'first_layer': 16}
0.976422 (0.007289) with: {'optimizer': 'adam', 'batch_size': 15, 'second_layer': 12, 'first_layer': 16}
0.954297 (0.036195) with: {'optimizer': 'adam', 'batch_size': 15, 'second_layer': 0, 'first_layer': 32}
0.976701 (0.010275) with: {'optimizer': 'adam', 'batch_size': 15, 'second_layer': 8, 'first_layer': 32}
0.974299 (0.011409) with: {'optimizer': 'adam', 'batch_size': 15, 'second_layer': 12, 'first_layer': 32}
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f216dbb6710>>
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 712, in __del__
TypeError: 'NoneType' object is not callable
